# -*- coding: utf-8 -*-
"""Training_only_knife.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a8pj59go26pHTnuHB93w0aqRQKVJSzUt
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="7WLwYOvv8HBpfBblxXkO")
project = rf.workspace("workspace-zqssx").project("knife-dataset-new")
dataset = project.version(1).download("yolov5")



# %cd /content/yolov5



# %cat /content/knife-dataset-new-1/data.yaml


# %cd /
from glob import glob
img_list = glob('/content/knife-dataset-new-1/train/images/*.jpg')
print(len(img_list))



with open('/content/train2.txt', 'w') as f:
  f.write('\n'.join('/content/knife-dataset-new-1/train/images') + '\n')

with open('/content/val2.txt', 'w') as f:
  f.write('\n'.join('/content/knife-dataset-new-1/valid/images') + '\n')




import yaml

with open('/content/knife-dataset-new-1/data.yaml', 'r') as f:
  data = yaml.safe_load(f)


print(data)
data['train'] = '/content/train2.txt'
data['valid'] = '/content/val2.txt'

with open('/content/data.yaml', 'w') as f:
  yaml.dump(data, f)

print(data)



# %cd /content/knife-dataset-new-1/
!python '/content/yolov5/train.py' --img 416 --batch 8 --epochs 50 --data /valid/data.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --name knife_yolov5s_results